name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Build Docker image
        run: docker build -t grocery-app-be .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin ${{ secrets.GROCERY_APP }}

      - name: Tag Docker image for ECR
        run: docker tag grocery-app-be:latest ${{ secrets.GROCERY_APP }}/grocery-app-be:latest

      - name: Push Docker image to Amazon ECR
        run: docker push ${{ secrets.GROCERY_APP }}/grocery-app-be:latest

      - name: Update ECS Service to Use Latest Image
        run: |
          aws ecs update-service --cluster ${{ secrets.CLUSTER_PROD }} --service ${{ secrets.SERVICE_PROD }} --force-new-deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-southeast-1


